# =================================================================== Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use, for example application-dev.yml if you use the "dev" profile. 
# =================================================================== 
# =================================================================== Standard Spring Boot properties. Full reference is available at: 
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html 
# ===================================================================
- hosts: 10.60.108.43
  remote_user: tiemchung
  tasks:
  - name: get file build artifact
    win_get_url:
     url: http://10.60.156.26:8081/repository/msbuild/TCQG_DEPLOY/TCQG_DEPLOY/1.{{VERSION}}/TCQG_DEPLOY-1.{{VERSION}}.zip
     dest: C:\inetpub\wwwroot\
  - name: Remove directory structure
    win_file:
     path: C:\Tiem Chung\NiisAuto8089\publish
     state: absent
  - name: unzip file build
    win_unzip:
     src: C:\inetpub\wwwroot\TCQG_DEPLOY-1.{{VERSION}}.zip
     dest: C:\Tiem Chung\NiisAuto8089\publish\
  - name: deploy app in IIS Server
    win_iis_website:
     name: TiemChung8089
     state: started
     port: 8089
     ip: 10.60.108.43
     application_pool: TiemChung8089
     physical_path: C:\Tiem Chung\NiisAuto8089\publish\PackageTmp
