# =================================================================== Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use, for example application-dev.yml if you use the "dev" profile. 
# =================================================================== 
# =================================================================== Standard Spring Boot properties. Full reference is available at: 
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html 
# ===================================================================
- hosts: 10.60.155.244
  remote_user: app
  tasks:
  - name: get file build artifact
    win_get_url:
     url: http://10.60.156.26:8081/repository/msbuild/{{GROUPID}}/{{GROUPID}}/1.{{VERSION}}/{{GROUPID}}-1.{{VERSION}}.zip
     dest: C:\TCMR
  # - name: backup folder code
  #   win_zip:
  #     src: C:\hoanv25\8080
  #     dest: C:\TCMR\8080_bk_{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}.zip
  - name: unzip file build to Web admin 8080
    win_unzip:
     src: C:\TCMR\{{GROUPID}}-1.{{VERSION}}.zip
     dest: C:\hoanv25\8080
  - name: Copy file web.config to Web Admin 8080
    win_shell: |
      xcopy "C:\TCMR\Web.config" "C:\hoanv25\8080" /Y
  #- name: unzip file build
  #  win_unzip:
  #   src: E:\TCMR\8080_bk_20191025-1734.zip
  #   dest: E:\Data\Builds\Web Admin\8080
  - name: deploy app in IIS Server
    win_iis_website:
     name: APP_8080
     state: restarted
     port: 8080
     ip: 10.60.156.244
     application_pool: APP_8080
     physical_path: C:\hoanv25\8080