- hosts: 10.60.156.159
  remote_user: app
  tasks:
  - name: Check process running
    shell: ps -ef | grep 'serviceEtc-0.0.1-SNAPSHOT.jar' | grep -v grep | awk '{print $2}'
    register: process_stat

  - name: Show captured processes
    debug:
      var: process_stat.stdout

  - name: stop service if process running
    shell: |
      cd /u01/app/DMDC/back-end
      ./service.sh stop
    when: process_stat.stdout != ""
  
  - name: backup old file
    shell: |
      cd /u01/app/DMDC/back-end
      if [ -f "serviceEtc-0.0.1-SNAPSHOT.jar" ]; then mv serviceEtc-0.0.1-SNAPSHOT.jar serviceEtc-0.0.1-SNAPSHOT.jar.bk$(date +%Y%m%d%H%M%S); fi;
  
  - name: get build artifact to tomcat
    get_url:
      url: http://10.60.156.26:8081/repository/msbuild/{{groupId}}/{{artifactId}}/1.{{BUILD_NUMBER}}/{{artifactId}}-1.{{BUILD_NUMBER}}.jar
      dest: /u01/app/DMDC/back-end/
  
  - name: rename file
    shell: |
      cd /u01/app/DMDC/back-end
      mv {{artifactId}}-1.{{BUILD_NUMBER}}.jar serviceEtc-0.0.1-SNAPSHOT.jar
  
  - name: start service serviceEtc-0.0.1-SNAPSHOT.jar
    shell: |
      cd /u01/app/DMDC/back-end
      ./service.sh start
  
  - name: get port config service
    shell: |
      cd /u01/app/DMDC/back-end
      ./service.sh status | grep 'APP_PORT' | awk '{print $1}' | grep -o '[[:digit:]]*'
    register: app_port
  
  - name: Wait for port {{app_port.stdout}} to become open on the host, don't start checking for 10 seconds
    wait_for:
     port: '{{app_port.stdout}}'
     delay: 10
     timeout: 300
  
  - name: check process running
    shell: |
      cd /u01/app/DMDC/back-end
      ./service.sh status | grep 'PID' | tail -1 | awk '{print $6}'
    register: service

  - name: success message
    debug: msg="ANSIBLE_DEPLOY_SUCCESS service running with PID:{{service.stdout}}"
    when: process_stat.stdout != ""
    


