apiVersion: v1
kind: Service
metadata:
  name: dmdc-backend
  labels:
    app: etc
    module: dmdc-backend
spec:
  ports:
  - name: dmdc-backend-port
    port: 8989
    protocol: TCP
    nodePort: 9752
  selector:
    app: etc
    module: dmdc-backend
  type: NodePort